name: Continuous Integration

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: yonatankarp/github-actions/.github/workflows/ci.yml@v1
    with:
      context: .
      build_dockerfile: false

  dependabot_auto_merge:
    needs: pipeline
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1
    secrets:
      DEPENDABOT_MERGE_TOKEN: ${{ secrets.REVIEWER_GITHUB_TOKEN }}

  linters:
    uses: yonatankarp/github-actions/.github/workflows/linters.yml@v1
