name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    uses:  yonatankarp/github-actions/.github/workflows/update-gradle-wrapper.yml@v1
