name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Update Gradle Wrapper
        # WARN: as this action comes from the org without public members and it has relatively few "stars",
        # so this specific SHA passed #infosec review from SumUp. Please do NOT upgrade this version unless
        # it is incompatible with our build - then we'll have to review the version diff.
        uses: gradle-update/update-gradle-wrapper-action@0407394b9d173dfc9cf5695f9f560fef6d61a5fe
        env:
          POS_PACKAGES_READ_TOKEN: ${{ secrets.CATALOG_BOT_READ_PACKAGE_GH_TOKEN }}
        with:
          repo-token: ${{ secrets.REVIEWER_GITHUB_TOKEN }}
